name: build-and-release-electron

on:
  push:
    paths:
      - "baklava/**"
    branches:
      - staging

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/cache@v2
        with:
          path: baklava/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('baklava/yarn.lock') }}
      - name: Install deps
        working-directory: baklava
        run: yarn
      - name: Install rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - name: Install nj-cli
        run: cargo install nj-cli
      - name: Build Globkey
        working-directory: baklava
        run: yarn build:globkey
      - name: Install Overlay Deps
        working-directory: baklava/resources/overlay
        run: yarn
      - name: Build overlay
        working-directory: baklava/resources/overlay
        run: yarn build
      - name: Prepare for app notarization
        if: startsWith(matrix.os, 'macos')
        # Import Apple API key for app notarization on macOS
        # this get skipped for some reason
        run: |
          mkdir -p ~/private_keys/
          echo '${{ secrets.api_key }}' > ~/private_keys/AuthKey_${{ secrets.api_key_id }}.p8
      # Uncomment the step below after getting the snapcraft package name for dogehouse and add 'snap' target to baklava/package.json
      # - name: Install Snapcraft
      #   uses: samuelmeuli/action-snapcraft@v1
      #   # Only install Snapcraft on Ubuntu
      #   if: startsWith(matrix.os, 'ubuntu')
      #   with:
      #     # Log in to Snap Store
      #     snapcraft_token: ${{ secrets.snapcraft_token }}
      - name: Compile Typescript
        working-directory: baklava
        run: yarn compile
      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}
          package_root: baklava
          github_token: ${{ secrets.github_token }}
          release: true
        env:
          # macOS notarization API key
          API_KEY_ID: ${{ secrets.api_key_id }}
          API_KEY_ISSUER_ID: ${{ secrets.api_key_issuer_id }}