name: end-to-end-tests
on:
  push:
    branches:
      - staging
    paths:
      - 'kousa/lib/**'
      - 'kibbeh/src/**'
  pull_request:
    branches:
      - staging
    paths:
      - 'kousa/lib/**'
      - 'kibbeh/src/**'
jobs:
  test:
    name: end-to-end-tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./kousa
    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-elixir@v1
      with:
        otp-version: '22.2'
        elixir-version: '1.11'
    - name: fetch deps
      run: mix deps.get
      env:
          MIX_ENV: test
    - run: source .envrc && mix start server
      id: mix
    - name: Use Node.js
      uses: actions/setup-node@v1
    - run: yarn install
    - run: cd ../kebab && yarn build
    - run: cd ../kibbeh && yarn dev
    - run: cd ../kibbeh && yarn cy:run