name: kibbeh:lint_and_test

on:
  push:
    branches:
      - staging
    paths:
      - "kibbeh/**"
  pull_request:
    branches:
      - staging
    paths:
      - "kibbeh/**"

jobs:
  test:
    name: lint-and-test-kibbeh
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install
      - run: cd kebab && yarn build
      - run: cd dolma && yarn build
      - run: cd kibbeh && yarn compile
      - run: cd kibbeh && yarn lint
      - run: cd kibbeh && yarn test:ci
        id: test
